### ISSUE TITLE
Work distribution

### ISSUE THREAD

**Issue by VGTN-Vidanagama** [dbasemsys/biz_v#1]
Distribute the log items to team members as issues here

**Comment by dbasemsys** [comment]
We didn't get you clearly sir.

This is what we understood. If you ask to do the project in branch wise collaboration, actually we already started working that way. Unfortunately, in the middle of 2nd sprint, we got kind of merging issues. 

So that we hold the branch wise working on GitHub and started working on our project. Now we've completed our project and we pushed it into this Repository. But We still have our old Repository which has the merge conflicts. 
Old GitHub Repository Link : https://github.com/dbasemsys/biz

Please have a look.
Please let us know if anything to consider.

Thank you.

**Comment by VGTN-Vidanagama** [comment]
If you need to branch it is also fine. if you have issues with it, no need.
The tasks/log items assigned to each member should be added to the "Issues" tab for easy tracking of contributions.

**Comment by dbasemsys** [comment]
Sure Sir. We're working on it.
